### PR TITLE
add aggregation/genie for Chinese

### PR DESCRIPTION
**Pull request by johnnychhsu**
add aggregation/genie for Chinese

### CODE REVIEW

**Comment by johnnychhsu** [comment]
For average case, why one is set turking but the other one is not?
https://github.com/Stanford-Mobisocial-IoT-Lab/genie-toolkit/blob/master/languages/en/aggregation.genie#L47

**Comment by gcampax** [comment]
"mean" is somewhat of a technical word, so we tought it would be unsafe to show to turkers, but it's a fine word to include in the synthetic set.

**Comment by johnnychhsu** [comment]
I see. I am done with this.

**Comment by rayslxu** [comment]
oh, btw, probably change the license & author at the top? don't give all the credit of your work to Giovanni, right? :)

**Comment by johnnychhsu** [comment]
yeah XD Thank you!!

**Pull request merged**
